import type { Metadata } from "next";
import "./globals.css";
import AppBar from "src/components/AppBar/AppBar"

export const metadata: Metadata = {
  title: process.env.ENV_APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
      <link rel="preconnect" href="https://fonts.bunny.net" />
      <link href="https://fonts.bunny.net/css?family=nunito:300,400,500,600,700,800" rel="stylesheet" />
      </head>
      <body
      className="antialiased"
      >
      <AppBar />
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
